# Generated by Django 6.0.1 on 2026-01-19 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始使用时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='预计结束时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='时长(小时)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已预约'), ('in_use', '使用中'), ('completed', '已完成'), ('cancelled', '已取消'), ('overdue', '逾期未取')], default='pending', max_length=20, verbose_name='订单状态')),
                ('payment_method', models.CharField(blank=True, choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('balance', '余额支付'), ('free', '免费')], max_length=20, null=True, verbose_name='支付方式')),
                ('pickup_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='取件码')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinets.cabinet', verbose_name='储物柜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
