# Generated by Django 6.0.1 on 2026-01-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_id', models.CharField(max_length=20, unique=True, verbose_name='柜子编号')),
                ('size', models.CharField(choices=[('small', '小柜（放背包）'), ('medium', '中柜（放行李箱）'), ('large', '大柜（放多个行李）')], max_length=10, verbose_name='尺寸规格')),
                ('location', models.CharField(max_length=100, verbose_name='位置描述')),
                ('station', models.CharField(max_length=50, verbose_name='所属站点')),
                ('status', models.CharField(choices=[('available', '空闲'), ('in_use', '使用中'), ('maintenance', '维护中'), ('offline', '离线')], default='available', max_length=20, verbose_name='状态')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=2.0, max_digits=6, verbose_name='单价')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='绑定设备ID')),
                ('is_locked', models.BooleanField(default=True, verbose_name='是否锁定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '储物柜',
                'verbose_name_plural': '储物柜',
                'ordering': ['station', 'cabinet_id'],
            },
        ),
    ]
