# Generated by Django 6.0.1 on 2026-01-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='has_item',
            field=models.BooleanField(blank=True, null=True, verbose_name='柜内是否有物品'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='item_detected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='物品检测时间'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='lock_angle',
            field=models.IntegerField(default=0, verbose_name='锁舌角度(0-360度)'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='lock_locked',
            field=models.BooleanField(default=True, verbose_name='电机锁是否锁定'),
        ),
    ]
