# Generated by Django 6.0.1 on 2026-01-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='设备ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='设备名称')),
                ('station', models.CharField(max_length=50, verbose_name='所属站点')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置描述')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '故障')], default='offline', max_length=20, verbose_name='在线状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='API密钥')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='电量百分比')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bound_cabinets', models.ManyToManyField(related_name='devices', to='cabinets.cabinet', verbose_name='绑定柜子')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['station', 'device_id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('open', '开柜'), ('close', '关柜'), ('heartbeat', '心跳'), ('status', '状态上报'), ('error', '错误')], max_length=20, verbose_name='日志类型')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='附加数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备日志',
                'verbose_name_plural': '设备日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
